# Generated by Django 5.1.5 on 2025-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('context', models.TextField(verbose_name='blog context')),
                ('ia_archived', models.BooleanField(default=False, verbose_name='is archived')),
            ],
        ),
    ]
